[package]
name = "http-fs-hello"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[workspace] # Exclude this project from the outer workspace

[dependencies]
wstd = "0.6.3"
