apiVersion: runtime.wasmcloud.dev/v1alpha1
kind: WorkloadDeployment
metadata:
  name: http-fs-hello
spec:
  replicas: 1
  template:
    spec:
      hostSelector:
        hostgroup: public-ingress
      volumes:
        - name: wasmcloud-data
          hostPath:
            path: /host-path/to/assets
      components:
        - name: http-fs-hello
          image: ghcr.io/ericgregory/http-fs-hello:0.1.1
          localResources:
            volumeMounts:
              - name: wasmcloud-data
                mountPath: /assets
      hostInterfaces:
        - namespace: wasi
          package: http
          interfaces:
            - incoming-handler
          config:
            host: localhost
